version: "3.8"

services:
  email-service:
    build: .
    container_name: email-service
    networks:
      - kafka_kafka_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29092,host.docker.internal:39092,host.docker.internal:49092
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

networks:
  kafka_kafka_network:
    external: true
