spring.application.name=email

# SMTP configuration (rellenar con credenciales reales o variables de entorno)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=marabbitholeil@gmail.com
spring.mail.password=bsco egfl vgae xabw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# Kafka configuration
spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.kafka.consumer.group-id=email-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
